const tarotCardMeanings = [
  {
    name: "card1",
    img: require('../cardImages/card1.jpg'),
    love: " The Ace of Cups signifies the start of new emotional beginnings, representing a time of overflowing love, deep emotional connections, and the potential for profound emotional fulfillment in relationships. It suggests the arrival of a significant emotional connection that brings joy and contentment.",
    money: "In terms of finances, the Ace of Cups indicates financial opportunities that are deeply fulfilling and emotionally rewarding. It represents investments or financial endeavors that align with one's heart's desires, bringing both financial and emotional satisfaction. ",
    career:"In a career context, the Ace of Cups suggests embracing a career path that ignites passion and emotional fulfillment. It encourages following one's creative aspirations and pursuing work that brings joy and satisfaction on a profound level.",
  },
  {
    name: "card2",
    img: require('../cardImages/card2.jpg'),
    love: " The Ace of Pentacles signifies the beginning of a solid and prosperous foundation in love. It represents a new relationship or a deepening commitment that brings stability, security, and long-term potential. It suggests a love connection that supports and nurtures growth.",
    money: "In terms of finances, the Ace of Pentacles indicates new financial opportunities, material abundance, and the potential for financial prosperity. It represents the manifestation of wealth and the start of a stable and prosperous financial journey. ",
    career: "In a career context, the Ace of Pentacles suggests new career opportunities or the potential for financial rewards and stability. It symbolizes the start of a successful and fulfilling career path, where skills and efforts are rewarded with material and professional growth.",
  },
  {
    name: "card3",
    img: require('../cardImages/card3.png'),
    love: " The Ace of Swords represents mental clarity, breakthroughs, and new perspectives in love. It signifies a moment of truth, clear communication, and the potential for a fresh start or a new way of thinking within relationships. It suggests the power of honest and open dialogue in fostering understanding and resolving conflicts. ",
    money: "Financially, the Ace of Swords indicates breakthroughs and new opportunities in money matters. It represents the potential for financial success through strategic thinking, decisive action, and clear communication. It encourages embracing innovative ideas and making informed financial decisions that lead to growth and abundance.",
    career: "In a career context, the Ace of Swords represents a new direction or breakthrough in one's professional path. It suggests the power of clear communication, logical thinking, and innovative ideas in the workplace. It encourages embracing intellectual challenges, taking decisive action, and using one's mental acuity to achieve professional success and overcome obstacles.",
  },
  {
    name:"card4",
    img: require("../cardImages/card4.jpg"),
    love: "The Ace of Wands represents passion, inspiration, and new beginnings in love. It signifies the ignition of a passionate and dynamic relationship or the awakening of creative and romantic energies within an existing partnership. It suggests embracing enthusiasm and taking bold action to nurture love and spark exciting new possibilities.",
    money:"Financially, the Ace of Wands indicates new financial opportunities or ventures that align with one's passions and creative talents. It represents the potential for financial abundance and success through innovative ideas, entrepreneurial endeavors, or career paths that ignite one's passion. It encourages taking decisive action and harnessing enthusiasm to manifest financial growth and prosperity.",
    career:"In a career context, the Ace of Wands represents new professional opportunities or ventures that align with one's passions and talents. It suggests a dynamic and creative approach to work, where one's enthusiasm and energy are harnessed to pursue ambitious goals. It encourages embracing new challenges, taking bold initiatives, and channeling one's passion into meaningful and fulfilling career endeavors.",
  },
  {
    name:"card5",
    img: require("../cardImages/card5.jpg"),
    love: "The Two of Cups represents soulmates, deep connections, and mutual understanding in relationships. It symbolizes the harmonious union of two souls, emphasizing the importance of emotional balance, respect, and shared values. It signifies a relationship based on love, trust, and a deep emotional connection.",
    money:"When it comes to money, the Two of Cups indicates financial partnerships or collaborations that bring both emotional and financial balance. It suggests the potential for joint financial ventures or investments that align with shared goals and values, resulting in mutual prosperity and fulfillment.",
    career:"In terms of career, the Two of Cups suggests collaborative or partnership-based career opportunities. It signifies working harmoniously with others, fostering supportive relationships in the workplace, and finding fulfillment through cooperative projects or teamwork.",
  },
  {
    name:"card6",
    img: require("../cardImages/card6.jpg"),
    love: "The Two of Pentacles represents balance, adaptability, and the need for flexibility in love. It signifies the juggling of responsibilities and priorities within a relationship, emphasizing the importance of finding harmony and managing commitments. It suggests maintaining a sense of humor and being open to change.",
    money:"Financially, the Two of Pentacles indicates the need to find balance and make wise financial choices. It suggests managing resources efficiently and being adaptable in the face of financial fluctuations. It encourages finding creative solutions to financial challenges and maintaining a steady and adaptable approach.",
    career:"In terms of career, the Two of Pentacles suggests balancing multiple projects or responsibilities in the workplace. It emphasizes the need for adaptability and finding a harmonious balance between professional commitments. It encourages being flexible, organized, and open to change in order to navigate successfully through work-related challenges and responsibilities.",
  },
  {
    name:"card7",
    img: require("../cardImages/card7.png"),
    love: "The Two of Swords represents a stalemate, difficult choices, and the need for clarity in love. It signifies a period of indecision or conflicting emotions within a relationship. It suggests the importance of seeking balance, examining different perspectives, and making choices that align with one's values and personal growth. It encourages finding clarity and resolution in order to move forward.",
    money:"Financially, the Two of Swords indicates financial choices or a dilemma that requires careful consideration. It suggests the need to weigh options, gather information, and make informed financial decisions. It encourages seeking professional advice or conducting thorough research to overcome financial challenges and find a path forward.",
    career:"In terms of career, the Two of Swords represents a period of indecision or uncertainty in professional matters. It suggests the need to carefully assess options, evaluate different perspectives, and gather information before making important career decisions. It encourages finding a balance between intuition and logic, seeking clarity, and making choices that align with long-term professional goals and personal values.",
  },
  {
    name:"card8",
    img: require("../cardImages/card8.jpg"),
    love: "The Two of Wands represents partnership, personal power, and planning in love. It signifies a period of collaboration and shared visions within a relationship, where partners align their goals and harness their individual strengths to create a harmonious and successful union. It suggests the importance of strategic planning, communication, and mutual respect.",
    money:"Financially, the Two of Wands indicates financial planning and the need to make strategic decisions to achieve long-term financial stability and growth. It represents exploring investment opportunities, partnership ventures, or expanding one's financial horizons. It encourages setting clear financial goals, utilizing foresight, and making choices that align with long-term financial success.",
    career:"In terms of career, the Two of Wands represents collaborative partnerships or professional relationships that enhance one's career prospects. It suggests aligning goals with colleagues or superiors, utilizing strategic planning, and exploring new avenues for professional growth. It encourages harnessing personal power, taking calculated risks, and embracing opportunities that expand professional horizons and lead to long-term career success.",
  },
  {
    name:"card9",
    img: require("../cardImages/card9.jpg"),
    love: "The Three of Cups represents celebration, joy, friendship, and a sense of community in love. It symbolizes deep emotional connections with others, often in the context of friendships or group dynamics. It signifies the importance of shared experiences, mutual support, and the celebration of love and emotional bonds.",
    money:"Financially, the Three of Cups signifies financial abundance and shared financial success through cooperative ventures. It suggests financial opportunities that arise from connections, partnerships, or working together with others. It emphasizes the benefits of collaboration and the potential for financial growth and prosperity through social connections or community-based efforts.",
    career:" In a career context, the Three of Cups signifies careers in event planning, entertainment, or professions that involve working in a team-oriented and supportive work environment. It suggests finding fulfillment through collaboration, enjoying harmonious relationships with colleagues, and experiencing professional success through shared achievements.",
  },
  {
    name:"card10",
    img: require("../cardImages/card10.jpg"),
    love: "The Three of Pentacles represents teamwork, collaboration, and the rewards of joint efforts in love. It signifies a harmonious partnership, where each person contributes their unique skills and talents to create a strong and fulfilling relationship. It suggests a relationship based on trust, cooperation, and mutual growth.",
    money:"Financially, the Three of Pentacles indicates financial rewards through collaborative efforts or joint ventures. It represents the successful completion of a project, leading to financial stability and recognition. It encourages utilizing one's skills and expertise in partnerships or collaborative financial opportunities for long-term success.",
    career:"In a career context, the Three of Pentacles represents working in a team or collaborative environment, where everyone's contributions are valued and recognized. It suggests professional success through cooperation, coordination, and mutual support. It encourages fostering positive working relationships, sharing knowledge and expertise, and striving for excellence in a collaborative work setting.",
  },
  {
    name:"card11",
    img: require("../cardImages/card11.png"),
    love: "The Three of Swords represents heartbreak, emotional pain, and sorrow in love. It signifies a period of grief or loss within a relationship, often resulting from a betrayal, separation, or emotional upheaval. It suggests the need for healing, processing emotions, and finding ways to move forward with self-compassion and resilience. ",
    money:"Financially, the Three of Swords indicates financial challenges or setbacks that bring emotional pain and disappointment. It suggests the need to reassess financial strategies, seek support, and find healthy ways to cope with financial stress. It encourages focusing on emotional healing and exploring alternative solutions to overcome financial difficulties. ",
    career:"In a career context, the Three of Swords represents a period of professional disappointment or setbacks. It suggests navigating through career challenges, processing emotions related to work-related issues, and finding ways to regain professional stability and fulfillment. It encourages self-care, seeking support, and exploring new opportunities for growth and career advancement.",
  },
  {
    name:"card12",
    img: require("../cardImages/card12.jpg"),
    love: "The Three of Wands represents progress, expansion, and exploration in love. It signifies a period of growth and optimism within a relationship, where partners embark on new adventures and explore uncharted territories together. It suggests the importance of open-mindedness, adaptability, and a shared sense of excitement and anticipation.",
    money:"Financially, the Three of Wands indicates financial growth and expansion. It represents the fruition of previous investments or business endeavors, leading to increased financial stability and abundance. It encourages exploring new financial opportunities, embracing innovative ideas, and having the foresight to seize advantageous financial prospects.",
    career:"In a career context, the Three of Wands represents professional growth, expansion, and the exploration of new career opportunities. It suggests a period of progress and advancement, where one's efforts and strategic planning begin to bear fruit. It encourages embracing new challenges, seeking innovative solutions, and having the confidence to step into uncharted professional territories for further growth and success.",
  },
  {
    name:"card13",
    img: require("../cardImages/card13.png"),
    love: "The Four of Cups represents emotional introspection or contemplation in love. It suggests a period of reflecting on one's emotional needs, desires, and a search for deeper emotional fulfillment. It encourages taking a step back to reassess the current state of relationships and seek greater emotional satisfaction.",
    money:" Financially, the Four of Cups may indicate a sense of financial stagnation or boredom. It suggests a dissatisfaction with the current financial situation and a need to reevaluate goals and priorities to achieve greater financial fulfillment. It encourages exploring new financial opportunities and being open to changes that can bring about greater financial satisfaction.",
    career:"In terms of career, the Four of Cups may represent a career that may feel stagnant or unfulfilling. It suggests a need to explore new professional avenues or find ways to infuse greater emotional satisfaction into the current career path. It encourages introspection and seeking opportunities that align with personal passions and emotional well-being.",
  },
  {
    name:"card14",
    img: require("../cardImages/card14.jpg"),
    love: "The Four of Pentacles represents stability, security, and the need to protect what is cherished in love. It signifies a desire for stability and control within a relationship, which can bring both emotional security and potential challenges related to possessiveness. It suggests finding a healthy balance between holding onto what is valuable and allowing for growth and change. ",
    money:"Financially, the Four of Pentacles indicates financial stability and the accumulation of wealth. It suggests the need to manage finances wisely, while also being mindful of not becoming overly possessive or restrictive with money. It encourages finding a balance between saving and enjoying the fruits of one's labor.",
    career:"In terms of career, the Four of Pentacles suggests a need for stability and security in the professional realm. It emphasizes the importance of preserving one's position or resources, but also warns against becoming too rigid or resistant to change. It encourages finding a balance between stability and adaptability in order to achieve long-term career success. ",
  },
  {
    name:"card15",
    img: require("../cardImages/card15.png"),
    love: "The Four of Swords represents rest, recuperation, and introspection in love. It signifies a period of taking a step back from relationships, seeking solace, and finding emotional healing. It suggests the importance of self-care, setting healthy boundaries, and allowing time for reflection and personal growth within a relationship.",
    money:"Financially, the Four of Swords indicates a need for financial stability and conservation. It suggests taking a break from financial activities, setting aside money for future security, and assessing financial goals and strategies. It encourages finding a balance between saving and spending, prioritizing financial well-being, and embracing a cautious approach to money management.",
    career:"In terms of career, the Four of Swords represents a need for rest and rejuvenation in the professional realm. It suggests taking a break from work-related stress, finding time for self-reflection, and evaluating professional goals and aspirations. It encourages seeking work-life balance, implementing self-care practices, and creating a harmonious and healthy work environment to promote productivity and personal well-being.",
  },
  {
    name:"card16",
    img: require("../cardImages/card16.jpg"),
    love: "The Four of Wands represents celebration, harmony, and stability in love. It signifies a period of joyous and harmonious energy within a relationship, often marked by milestones, celebrations, or a strong sense of unity. It suggests the importance of creating a stable and supportive foundation for love to thrive.",
    money:"Financially, the Four of Wands indicates financial stability and security. It represents the rewards of hard work, prudent financial management, and successful endeavors. It encourages celebrating financial achievements, enjoying the fruits of one's labor, and building upon a solid financial foundation for future growth. ",
    career:"In terms of career, the Four of Wands represents a harmonious and supportive work environment. It suggests a time of professional celebrations, achievements, or recognition for one's efforts. It encourages fostering positive relationships with colleagues or superiors, creating a sense of camaraderie, and establishing a stable and supportive professional foundation for long-term success.",
  },
  {
    name:"card17",
    img: require("../cardImages/card17.jpg"),
    love: "The Five of Cups represents grief, disappointment, and emotional setbacks in love. It signifies a period of mourning or feeling emotionally let down in relationships. It suggests the need to process and heal emotional wounds before moving forward towards new beginnings.",
    money:"Financially, the Five of Cups may indicate financial loss or setbacks that lead to disappointment or a sense of scarcity. It encourages reassessing the current financial situation and finding ways to rebuild and recover from financial setbacks. It advises seeking support and focusing on emotional healing in order to regain financial stability.",
    career:"In a career context, the Five of Cups suggests a career disappointment or setback that leads to emotional turmoil. It signifies the need to process and navigate through emotions, seeking guidance and support during this challenging time. It encourages embracing resilience, learning from the experience, and exploring new career possibilities with renewed emotional strength.",
  },
  {
    name:"card18",
    img: require("../cardImages/card18.jpg"),
    love: "The Five of Pentacles represents hardship, lack, and the need for support in love. It signifies a period of emotional or financial challenges within a relationship, where partners may be facing difficulties and feeling excluded or isolated. It suggests the importance of seeking support and finding strength together during tough times. ",
    money:"Financially, the Five of Pentacles indicates financial struggles, setbacks, or a sense of lack. It suggests the need for careful budgeting, seeking assistance when necessary, and finding alternative ways to overcome financial difficulties. It encourages resilience and seeking support to improve financial circumstances. ",
    career:"In a career context, the Five of Pentacles suggests professional challenges or a feeling of exclusion in the workplace. It signifies a need for resilience and perseverance during difficult times. It encourages seeking support, exploring new opportunities, and finding alternative ways to overcome career obstacles and regain stability.",
  },
  {
    name:"card19",
    img: require("../cardImages/card19.png"),
    love: "The Five of Swords represents conflict, defeat, and power struggles in love. It signifies a period of discord, disagreements, or manipulation within relationships. It suggests the need for assertiveness, setting boundaries, and choosing battles wisely to protect one's emotional well-being. It encourages seeking peaceful resolutions and fostering open and honest communication.",
    money:" Financially, the Five of Swords indicates financial losses, disputes, or unethical practices. It suggests the need for caution and careful assessment of financial situations. It encourages seeking fair and equitable solutions, protecting financial interests, and learning from past financial mistakes.",
    career:"In a career context, the Five of Swords represents workplace conflicts, power struggles, or feelings of defeat. It suggests the importance of assertiveness, setting clear boundaries, and addressing conflicts in a diplomatic manner. It encourages seeking resolutions that promote a harmonious work environment, learning from challenges, and focusing on personal growth and development to overcome professional setbacks.",
  },
  {
    name:"card20",
    img: require("../cardImages/card20.jpg"),
    love: "The Five of Wands represents conflict, competition, and challenges in love. It signifies a period of disagreement or power struggles within a relationship, where different opinions and interests clash. It suggests the need for open communication, compromise, and finding constructive ways to resolve conflicts.",
    money:"Financially, the Five of Wands indicates financial competition or conflicts that may arise. It suggests the need to be cautious in financial dealings, maintain ethical practices, and avoid getting caught up in unhealthy financial competition. It encourages seeking fair resolutions, focusing on one's own financial goals, and using conflicts as opportunities for personal growth and learning. ",
    career:"In a career context, the Five of Wands represents professional competition, disagreements, or clashes of ideas. It suggests the importance of finding common ground, embracing open communication, and working collaboratively to overcome challenges. It encourages seeking constructive solutions, valuing diverse perspectives, and using conflicts as opportunities to foster innovation and professional growth.",
  },
  {
    name:"card21",
    img: require("../cardImages/card21.jpg"),
    love: "The Six of Cups represents nostalgia, fond memories, and a focus on the past or childhood connections in love. It symbolizes the joy of reliving pleasant memories and a sense of innocence, purity, and emotional fulfillment in relationships. It suggests finding happiness through emotional connections rooted in the past.",
    money:"Financially, the Six of Cups signifies financial generosity or support, often in the form of receiving financial help or assistance. It may represent an unexpected financial gift or a sharing of resources that brings emotional and financial fulfillment.",
    career:"In terms of career, the Six of Cups may indicate a career that involves working with children, nurturing others, or finding fulfillment through supporting and helping others. It suggests creating a work environment that evokes positive emotions and tapping into creative and innocent aspects of oneself to find professional fulfillment.",
  },
  {
    name:"card22",
    img: require("../cardImages/card22.jpg"),
    love: "The Six of Pentacles represents generosity, giving, and receiving in love. It signifies a balanced and mutually supportive relationship, where partners offer each other emotional and material support. It suggests the importance of fairness, equality, and gratitude within a relationship. ",
    money:"Financially, the Six of Pentacles indicates financial generosity, receiving financial assistance, or having the means to help others. It suggests finding a balance between giving and receiving, and cultivating an attitude of abundance and gratitude. It encourages using financial resources wisely and sharing them with others when possible.",
    career:"In terms of career, the Six of Pentacles suggests a fair and supportive work environment, where colleagues or superiors value one's contributions. It represents receiving recognition, rewards, or promotions based on one's skills and efforts. It encourages cultivating a sense of generosity and sharing knowledge or resources to foster a harmonious and successful professional atmosphere.",
  },
  {
    name:"card23",
    img: require("../cardImages/card23.png"),
    love: "The Six of Swords represents transition, moving on, and finding solace in love. It signifies a period of leaving behind emotional turmoil or difficult situations within a relationship. It suggests finding peace, healing, and emotional growth as one moves towards a more positive future. It encourages embracing change and trusting in the journey of personal transformation.",
    money:"Financially, the Six of Swords indicates financial stability and a positive transition towards improved financial circumstances.It represents moving away from financial difficulties or hardships towards a more stable and secure financial situation. It encourages embracing financial changes, seeking opportunities for growth, and trusting in the process of financial transformation.",
    career:"In terms of career, the Six of Swords represents a professional transition or a period of moving away from challenging work environments. It suggests finding solace and growth in a new job or career path. It encourages embracing change, seeking professional support, and trusting in the process of career development and personal growth to navigate towards a more fulfilling and harmonious professional future. ",
  },
  {
    name:"card24",
    img: require("../cardImages/card24.jpg"),
    love: "The Six of Wands represents victory, recognition, and triumph in love. It signifies a period of success, public affirmation, or a sense of accomplishment within a relationship. It suggests the importance of celebrating achievements, embracing confidence, and sharing the joy of success with loved ones.",
    money:"Financially, the Six of Wands indicates financial success, recognition, or the fulfillment of financial goals. It represents the rewards of hard work and the achievement of financial stability or abundance. It encourages embracing confidence, celebrating financial victories, and using success as a stepping stone for further growth and accomplishment. ",
    career:"In terms of career, the Six of Wands represents professional recognition, victory, and public acclaim. It suggests a period of career success, where one's efforts and achievements are acknowledged and celebrated. It encourages embracing self-confidence, showcasing professional skills, and using recognition as a catalyst for further professional growth and advancement.",
  },
  {
    name:"card25",
    img: require("../cardImages/card25.jpg"),
    love: "The Seven of Cups represents fantasy, illusion, and a need for discernment and clarity in love. It signifies a time of confusion, choices, and the need to sift through various emotional possibilities or illusions to determine what truly aligns with one's heart's desires. It encourages making decisions from a place of emotional clarity. ",
    money:"Financially, the Seven of Cups indicates financial choices or opportunities that require careful consideration. It advises being discerning and avoiding get-rich-quick schemes or ventures that may seem too good to be true. It encourages focusing on realistic financial goals and avoiding distractions that may hinder financial growth.",
    career:" In a career context, the Seven of Cups suggests career choices that involve creative pursuits, multiple options, or a need to focus on clarity and discernment in professional decisions. It emphasizes the importance of staying grounded, evaluating opportunities carefully, and choosing a career path that aligns with one's true passions and aspirations.",
  },
  {
    name:"card26",
    img: require("../cardImages/card26.jpg"),
    love: " The Seven of Pentacles represents patience, perseverance, and the need for assessment in love. It signifies a period of waiting, reflection, and evaluating the progress of a relationship. It suggests the importance of allowing things to unfold naturally and being patient in order to see the fruits of one's emotional investments. ",
    money:"Financially, the Seven of Pentacles indicates a time of waiting and assessing the progress of financial endeavors. It suggests the need to have patience and perseverance in financial matters, and to evaluate the effectiveness of one's investments or financial strategies. It encourages long-term thinking and being willing to make adjustments for future growth.",
    career:"In a career context, the Seven of Pentacles represents a need for patience and assessment in professional matters. It suggests taking a step back to evaluate the progress of one's career goals and projects. It encourages being patient during periods of growth and development, while also assessing whether adjustments or changes are needed to achieve long-term success.",
  },
  {
    name:"card27",
    img: require("../cardImages/card27.png"),
    love: "The Seven of Swords represents deception, trickery, and hidden agendas in love. It signifies a period of mistrust, betrayal, or dishonesty within a relationship. It suggests the need to be vigilant, assertive, and protective of one's emotional well-being. It encourages setting clear boundaries, confronting deception, and seeking honesty and transparency in order to restore trust. ",
    money:"Financially, the Seven of Swords indicates financial dishonesty, theft, or loss. It suggests the need for caution and vigilance in financial matters. It encourages protecting one's financial interests, being discerning with investments or financial partnerships, and seeking professional advice to mitigate financial risks.",
    career:"In a career context, the Seven of Swords represents professional deceit, office politics, or hidden agendas. It suggests being cautious of colleagues or superiors who may not have your best interests at heart. It encourages maintaining integrity, protecting your professional reputation, and seeking opportunities that align with your values and long-term career goals.",
  },
  {
    name:"card28",
    img: require("../cardImages/card28.jpg"),
    love: "The Seven of Wands represents courage, resilience, and standing up for what you believe in love. It signifies a period of assertiveness, defending personal values, and overcoming challenges within a relationship. It suggests the importance of taking a stand, maintaining boundaries, and having the courage to fight for what is important to you. It encourages open and honest communication, assertiveness, and the willingness to address conflicts or obstacles in order to preserve the integrity of the relationship.",
    money:"Financially, the Seven of Wands indicates financial challenges or obstacles that require courage and resilience to overcome. It suggests the need to protect one's financial interests, stand up for one's values, and take proactive measures to navigate financial difficulties. It encourages perseverance, seeking alternative solutions, and using setbacks as opportunities for personal and financial growth.",
    career:"In a career context, the Seven of Wands represents professional challenges, competition, or resistance to one's ideas or goals. It suggests the need to assert oneself, stand up for one's beliefs, and defend one's professional integrity. It encourages maintaining confidence in one's abilities, advocating for one's ideas, and using obstacles as opportunities to showcase resilience and determination in achieving professional success.",
  },
  {
    name:"card29",
    img: require("../cardImages/card29.jpg"),
    love: "The Eight of Cups represents seeking emotional fulfillment, leaving behind unfulfilling relationships, and embarking on a journey of self-discovery and emotional growth. It suggests the need to follow one's heart's desires and seek greater emotional satisfaction, even if it means letting go of familiar but unfulfilling situations.",
    money:"Financially, the Eight of Cups may indicate financial sacrifices or walking away from financial stability in search of greater emotional fulfillment. It suggests that true wealth and abundance lie in aligning financial decisions with emotional well-being and personal growth.",
    career:"In terms of career, the Eight of Cups may signify a career change or leaving behind a stable job to pursue a more emotionally fulfilling or spiritually aligned path. It encourages embarking on a professional journey that aligns with one's true passions, even if it means stepping out of one's comfort zone and taking risks for personal and emotional growth.",
  },
  {
    name:"card30",
    img: require("../cardImages/card30.jpg"),
    love: "The Eight of Pentacles represents dedication, craftsmanship, and mastery in love. It signifies a committed and focused approach to relationships, where partners invest time and effort to nurture and develop their connection. It suggests the importance of continuous growth and improvement within a relationship.",
    money:"Financially, the Eight of Pentacles indicates financial dedication and a commitment to long-term financial goals. It represents hard work, discipline, and continuous learning to improve one's financial situation. It encourages developing skills, investing in personal growth, and striving for excellence in financial endeavors. ",
    career:"In terms of career, the Eight of Pentacles signifies a diligent and committed work ethic. It suggests a focus on professional development, honing one's skills, and striving for mastery in one's chosen field. It encourages a dedicated approach to work, continuous learning, and investing time and effort to achieve career advancement and success.",
  },
  {
    name:"card31",
    img: require("../cardImages/card31.png"),
    love: "The Eight of Swords represents restriction, self-imposed limitations, and feeling trapped in love. It signifies a period of emotional paralysis, self-doubt, or being unable to see the way forward within a relationship. It suggests the need to challenge limiting beliefs, break free from negative patterns, and embrace personal empowerment to find liberation.",
    money:"Financially, the Eight of Swords indicates financial limitations or feeling trapped in a challenging financial situation. It suggests the need to confront financial fears, expand one's financial perspective, and seek opportunities for financial growth and abundance. It encourages shifting one's mindset, taking calculated risks, and freeing oneself from self-imposed financial limitations. ",
    career:"In terms of career, the Eight of Swords represents feeling stuck or restricted in one's professional growth. It suggests self-imposed limitations, negative self-talk, or being unable to see opportunities for advancement. It encourages breaking free from limiting beliefs, seeking professional development opportunities, and embracing personal empowerment to overcome professional obstacles and achieve career success.",
  },
  {
    name:"card32",
    img: require("../cardImages/card32.jpg"),
    love: "The Eight of Wands represents swiftness, progress, and forward movement in love. It signifies a period of rapid developments, exciting communication, and the potential for a passionate and transformative relationship. It suggests the importance of embracing change, seizing opportunities, and maintaining an open and receptive mindset.",
    money:"Financially, the Eight of Wands indicates fast-paced financial growth and progress. It represents the potential for swift financial developments, successful ventures, or lucrative opportunities. It encourages embracing change, taking decisive action, and utilizing one's intuition to make the most of financial prospects. ",
    career:"In terms of career, the Eight of Wands represents swift progress and career advancement. It suggests a period of dynamic growth, where opportunities arise and projects move forward rapidly. It encourages embracing change, staying adaptable, and taking bold actions to propel one's career forward. It urges harnessing the energy of momentum, seizing opportunities, and maintaining focus and determination in achieving professional goals. ",
  },
  {
    name:"card33",
    img: require("../cardImages/card33.jpg"),
    love: "The Nine of Cups represents wishes fulfilled, emotional satisfaction, and contentment in love. It signifies a period of emotional abundance and deep fulfillment within relationships. It embodies the fulfillment of emotional desires and the joy that comes from experiencing profound love and emotional connection.",
    money:" Financially, the Nine of Cups indicates financial abundance and material comfort. It represents achieving financial goals and experiencing a state of financial security that brings emotional contentment. It suggests a time of financial satisfaction and the ability to enjoy the fruits of one's labor. ",
    career:"The Nine of Cups in a career reading signifies professional fulfillment and contentment, indicating that you have achieved success and are satisfied with your work. It suggests a period of material comfort and the ability to enjoy the rewards of your career accomplishments.",
  },
  {
    name:"card34",
    img: require("../cardImages/card34.jpg"),
    love: "The Nine of Pentacles represents independence, abundance, and self-sufficiency in love. It signifies a period of personal growth and self-empowerment within a relationship, where partners embrace their individuality while supporting each other's independence. It suggests a relationship that thrives on mutual respect and admiration.",
    money:"Financially, the Nine of Pentacles indicates financial independence, abundance, and material well-being. It represents enjoying the fruits of one's labor, financial stability, and a sense of accomplishment. It encourages embracing financial freedom and making choices that align with personal values and aspirations.",
    career:"In a career context, the Nine of Pentacles represents professional independence and success. It suggests a career path that allows for personal fulfillment, autonomy, and financial abundance. It encourages embracing one's unique talents and skills, and creating a work-life balance that supports overall well-being and personal growth.",
  },
  {
    name:"card35",
    img: require("../cardImages/card35.png"),
    love: "The Nine of Swords represents anxiety, worry, and sleepless nights in love. It signifies a period of emotional distress, guilt, or overthinking within a relationship. It suggests the need to address fears, seek support, and find healthy ways to manage stress and anxiety in order to restore emotional well-being. ",
    money:"Financially, the Nine of Swords indicates financial worries, debt, or financial anxieties. It suggests the need to confront financial fears, seek practical solutions, and develop a sound financial plan to alleviate financial stress. It encourages seeking professional advice, creating a budget, and practicing self-care to find emotional balance and financial stability.",
    career:"In a career context, the Nine of Swords represents work-related stress, anxiety, or fear of failure. It suggests the need to address work-related worries, seek support from colleagues or mentors, and find healthy coping mechanisms to manage professional stress. It encourages self-reflection, adopting stress-management techniques, and creating a supportive work environment to restore emotional well-being and professional fulfillment.",
  },
  {
    name:"card36",
    img: require("../cardImages/card36.jpg"),
    love: "The Nine of Wands represents resilience, perseverance, and determination in love. It signifies a period of strength and courage within a relationship, where partners demonstrate resilience in the face of challenges or setbacks. It suggests the importance of maintaining boundaries, protecting emotional well-being, and continuing to fight for the relationship. ",
    money:"Financially, the Nine of Wands indicates financial resilience and the ability to overcome obstacles or setbacks. It represents the need to stay determined and focused on financial goals, even in the face of adversity. It encourages protecting one's financial interests, seeking alternative solutions, and using past experiences as sources of strength and wisdom.",
    career:"In a career context, the Nine of Wands represents professional resilience, perseverance, and the ability to overcome obstacles. It suggests staying committed to one's professional goals, even when faced with challenges or setbacks. It encourages maintaining a strong work ethic, adapting to changing circumstances, and using past experiences to fuel determination and success in achieving career objectives.",
  },
  {
    name:"card37",
    img: require("../cardImages/card37.jpg"),
    love: "The Ten of Cups represents emotional fulfillment, harmony, and a happy and loving family or community. It signifies a deep sense of emotional connection and contentment within relationships, often involving a loving and supportive family dynamic. It symbolizes the ultimate fulfillment of emotional desires and a state of profound happiness and love.",
    money:" Financially, the Ten of Cups signifies financial stability and security. It represents a harmonious and prosperous financial situation that provides emotional and material abundance. It suggests a time of financial contentment and the fulfillment of financial goals that contribute to overall well-being and happiness.",
    career:"In a career context, the Ten of Cups represents a career that brings emotional fulfillment and satisfaction. It signifies working in a supportive and harmonious work environment, where colleagues feel like a close-knit family. It suggests finding joy and fulfillment in professional relationships and experiencing a sense of emotional fulfillment and contentment in one's chosen career path.",
  },
  {
    name:"card38",
    img: require("../cardImages/card38.jpg"),
    love: "The Ten of Pentacles represents wealth, family legacy, and long-term stability in love. It signifies a relationship that is deeply rooted in tradition, family values, and the potential for a prosperous and enduring partnership. It suggests the creation of a loving and supportive family unit or the fulfillment of long-held relationship goals.",
    money:"Financially, the Ten of Pentacles indicates financial abundance, wealth, and the enjoyment of material comforts. It represents the realization of long-term financial security, often through family inheritance or established financial foundations. It encourages creating a lasting financial legacy and providing support for future generations. ",
    career:"In terms of career, the Ten of Pentacles signifies a successful and stable career that brings financial security and professional fulfillment. It suggests a sense of accomplishment and a solid reputation in one's chosen field. It encourages creating a positive work environment, fostering long-term professional relationships, and contributing to the growth and prosperity of the organization or business.",
  },
  {
    name:"card39",
    img: require("../cardImages/card39.png"),
    love: "The Ten of Swords represents pain, betrayal, and the end of a cycle in love. It signifies a period of deep emotional wounds, loss, or the completion of a challenging relationship or situation. It suggests the need to embrace healing, release pain, and allow for new beginnings and personal transformation.",
    money:"Financially, the Ten of Swords indicates financial losses, bankruptcy, or the end of a financial cycle. It suggests the need to accept financial setbacks, learn from past mistakes, and focus on rebuilding financial stability. It encourages seeking professional guidance, embracing financial lessons, and being open to new opportunities for financial growth.",
    career:"In terms of career, the Ten of Swords represents a period of professional challenges, setbacks, or the end of a career cycle. It suggests the need to release attachment to past professional disappointments, embrace personal growth and transformation, and open oneself to new career possibilities. It encourages exploring new paths, seeking support and guidance, and using the lessons learned to create a fresh start and pursue professional fulfillment.",
  },
  {
    name:"card40",
    img: require("../cardImages/card40.jpg"),
    love: "The Ten of Wands represents burdens, responsibilities, and the need for delegation in love. It signifies a period of overwhelm or excessive responsibilities within a relationship. It suggests the importance of seeking support, delegating tasks, and finding a balance between personal needs and partnership obligations.",
    money:"Financially, the Ten of Wands indicates financial burdens or excessive responsibilities. It represents the need to reassess priorities, seek help when necessary, and delegate tasks to manage financial stress effectively. It encourages finding a healthy work-life balance, setting realistic goals, and releasing unnecessary financial burdens to regain a sense of financial well-being.",
    career:"In terms of career, the Ten of Wands represents work-related overwhelm or excessive responsibilities. It suggests the need to delegate tasks, seek support from colleagues or superiors, and establish boundaries to avoid burnout. It encourages finding a balance between professional obligations and personal well-being, prioritizing self-care, and streamlining tasks to regain a sense of professional fulfillment and work-life balance.",
  },
  {
    name:"card41",
    img: require("../cardImages/card41.jpg"),
    love: "The Chariot card embodies the unwavering willpower and determination that drives you towards personal growth and fulfillment in love. It empowers you to embrace your independence, nurture self-confidence, and take charge of your own happiness by seeking relationships that align with your values, allowing for deep and meaningful connections.",
    money:"Financially, the Chariot signifies the attainment of financial success through disciplined effort and strategic planning. It urges you to tap into your ambition, focus on long-term goals, and take decisive action, allowing you to navigate challenges with resilience and achieve monetary abundance. ",
    career:"In a career context, the Chariot represents a triumphant journey of professional advancement fueled by focused ambition and assertiveness. It highlights your ability to overcome obstacles, lead with confidence, and make strategic choices, propelling you towards the achievement of your career objectives and unlocking opportunities for growth and success.",
  },
  {
    name:"card42",
    img: require("../cardImages/card42.jpg"),
    love: "The Death card in matters of love, it holds the significant meaning of liberating oneself from stagnant or unhealthy relationships that hinder personal growth, thereby creating space for the potential of a fresh start and the emergence of a more authentic and fulfilling love connection.",
    money:"When it comes to finances, the Death card embodies the necessity for change and transformation within your financial circumstances, compelling you to release outdated strategies or attachments that no longer serve your financial well-being, and to embrace new opportunities that hold the promise of growth, prosperity, and a revitalized approach to managing your resources. ",
    career:"In the realm of career, the Death card signifies the conclusion of a particular phase or job, paving the way for the emergence of new professional opportunities and personal growth. It calls upon you to embrace the inevitability of change, adapt to the shifting circumstances around you, and utilize the ending as a catalyst for a profound metamorphosis in both your personal and career trajectory.",
  },
  {
    name:"card43",
    img: require("../cardImages/card43.jpg"),
    love: "The Devil card symbolizes temptation, bondage, and unhealthy patterns. In love, it warns of being trapped in toxic or codependent relationships, urging you to break free from destructive patterns and prioritize your well-being.",
    money:"Financially, the Devil card represents financial entanglements or unhealthy material attachments, reminding you to be cautious of excessive spending or being trapped in a cycle of debt. ",
    career:"In a career context, it suggests being aware of unhealthy power dynamics or negative influences in the workplace. It encourages you to break free from limiting beliefs or unhealthy work environments and strive for greater personal and professional freedom.",
  },
  {
    name:"card44",
    img: require("../cardImages/card44.jpg"),
    love: "The Emperor card represents authority, leadership, structure, and stability. In matters of love, it signifies the importance of finding a partner who provides a strong sense of security and reliability, someone who embodies qualities of leadership and establishes a structured and stable foundation for the relationship.  ",
    money:"Financially, the Emperor card signifies the need for disciplined financial management and a structured approach. It emphasizes the importance of establishing a solid financial foundation and making strategic decisions to ensure long-term stability, security, and prosperity.",
    career:"In a career context, the Emperor card symbolizes a position of power and leadership, urging you to embrace your own inner authority and confidently take charge of your professional path. It signifies the creation of a structured and organized work environment, where your leadership skills can thrive, leading to stability, success, and the realization of your career goals.",
  },
  {
    name:"card45",
    img: require("../cardImages/card45.jpg"),
    love: "The Empress card in love signifies nurturing and loving relationships. It represents a time of emotional fulfillment, harmony, and deep connections. It encourages you to embrace love with an open heart, create a loving and supportive environment, and cultivate a strong bond with your partner.",
    money:"In terms of finances, The Empress indicates financial abundance and material prosperity. It suggests that you have the potential for financial growth and stability. It may be a favorable time for investments, business ventures, or reaping the rewards of your hard work. The card advises you to embrace your natural talents and creativity to manifest financial success.",
    career:"The Empress card in a career context represents successful entrepreneurship and creativity. It indicates that your professional endeavors can flourish through your ability to nurture and bring new ideas to life. It encourages you to trust your instincts and take a compassionate and supportive approach in your work. The Empress card suggests that your career path may involve areas such as art, design, or leadership roles where you can foster growth and create a positive work environment.",
  },
  {
    name:"card46",
    img: require("../cardImages/card46.jpg"),
    love: "The Fool card in love represents a new beginning or fresh start in matters of the heart. It signifies a sense of adventure, spontaneity, and openness to new experiences in relationships. It encourages you to take risks, embrace the unknown, and trust in the journey of love. This card often indicates a period of excitement and exploration in romantic connections.",
    money:"In terms of finances, The Fool card suggests that financial risks may lead to unexpected outcomes. It advises caution and careful planning when it comes to money matters. While it may be tempting to take bold financial leaps, it is important to assess the potential risks and consequences before making impulsive decisions. This card reminds you to balance your optimism with practicality to avoid financial instability.",
    career:"The Fool card in a career context represents a period of exploration and following your passion. It signifies a fresh start or a new venture in your professional life. This card encourages you to take a leap of faith and embrace unconventional paths or opportunities. It suggests that by stepping outside of your comfort zone and being open to new experiences, you can discover your true calling and find success in your career. ",
  },
  {
    name:"card47",
    img: require("../cardImages/card47.jpg"),
    love: "The Hanged Man card in love represents a period of surrender, introspection, and a different perspective in matters of the heart. It suggests that you may need to let go of control, expectations, or old patterns in relationships. This card encourages you to pause, reflect, and see love from a new angle. It may indicate a time of waiting, sacrificing, or making necessary changes for personal growth before moving forward in your love life.",
    money:"In terms of finances, The Hanged Man suggests a need for a fresh perspective and a willingness to make sacrifices for long-term financial stability. It advises you to pause and reassess your financial goals, strategies, and spending habits. This card may indicate a period of waiting, financial delays, or a need to let go of certain financial attachments. By embracing a new approach and letting go of old beliefs, you can gain a different viewpoint that leads to improved financial outcomes.",
    career:"The Hanged Man card in a career context signifies a time of suspension, surrender, and a shift in perspective. It suggests that you may need to let go of old ways of thinking or approaches to your career. It may indicate a need to step back from your current professional path to gain clarity and insight.The Hanged Man card reminds you that sometimes, in order to move forward in your career, you must be willing to let go and approach things from a different angle.",
  },
  {
    name:"card48",
    img: require("../cardImages/card48.jpg"),
    love: "The Hermit card in love represents a period of introspection, solitude, and inner reflection. It suggests that you may need to take time for self-discovery and self-reflection in your relationships. This card encourages you to retreat from the noise and distractions of the outside world to gain a deeper understanding of your own needs, desires, and values. It may indicate a time of seeking solitude to find clarity and wisdom before pursuing or committing to a new relationship.",
    money:"In terms of finances, The Hermit signifies a need for careful financial planning, frugality, and a conservative approach. It advises you to take a step back and assess your financial situation objectively. This card suggests that you may benefit from seeking the advice of financial experts or mentors who can provide guidance in managing your resources wisely. It may also indicate a period of financial self-reliance and the need to make thoughtful decisions before making significant investments or financial commitments.",
    career:"The Hermit card in a career context represents a period of introspection, inner wisdom, and seeking guidance in your professional life. This card encourages you to engage in self-reflection, research, and learning. It may indicate a time of seeking guidance from mentors, taking a break to reassess your goals, or developing a more strategic and thoughtful approach to your career path. The Hermit card reminds you that solitude and introspection can lead to profound insights and help you find the right path forward in your professional life.",
  },
  {
    name:"card49",
    img: require("../cardImages/card49.jpg"),
    love: "The Hierophant card in love signifies commitment, tradition, and spiritual connection in relationships. It represents a time of seeking guidance, wisdom, and deeper understanding within the context of partnerships. This card encourages you to embrace traditional values, rituals, and shared beliefs that strengthen your bond with your partner. It may indicate a need for spiritual or religious exploration together.",
    money:"In terms of finances, The Hierophant suggests a focus on financial stability, responsibility, and following established systems. It advises you to adhere to conventional financial practices, seek advice from professionals, and approach money matters with a structured and disciplined mindset. This card signifies the importance of honoring financial commitments and seeking stability through traditional financial avenues.",
    career:"The Hierophant card in a career context represents conformity, structure, and adherence to established systems in your professional life. It suggests that following traditional career paths, seeking mentorship, and aligning with established protocols can lead to success. This card encourages you to seek guidance from experienced professionals or authority figures in your field. It may also indicate a time of learning, studying, or seeking certifications to deepen your expertise and advance in your career.",
  },
  {
    name:"card50",
    img: require("../cardImages/card50.jpg"),
    love: "The High Priestess card in love represents intuitive connections, deep emotional bonds, and trusting your inner wisdom. It suggests that in matters of the heart, it is important to listen to your intuition and follow your instincts. This card encourages you to embrace your inner wisdom and explore the depths of your emotions in relationships. It may indicate a need for introspection and tapping into your subconscious to uncover hidden desires or insights.",
    money:"In terms of finances, The High Priestess signifies financial stability through careful planning and intuition. It advises you to trust your instincts when it comes to money matters and make informed decisions. This card suggests that paying attention to the subtle signs and trusting your inner guidance can lead to favorable financial outcomes. It may also indicate the need for financial self-reliance and a balanced approach to managing your resources.",
    career:"The High Priestess card in a career context represents trusting your instincts and using intuition to make career decisions. It suggests that in your professional life, it is important to tap into your inner wisdom and listen to your gut feelings. This card encourages you to pay attention to the deeper meaning behind situations and to trust the guidance that arises from within. It may indicate a time of seeking mentorship, developing your intuitive abilities, or trusting your instincts to make strategic career moves.",
  },
  {
    name:"card51",
    img: require("../cardImages/card51.jpg"),
    love: "The Judgment card in love represents a period of transformation, forgiveness, and awakening in relationships. It signifies a time of self-reflection and evaluating past choices and behaviors. This card encourages you to let go of past resentments, embrace self-forgiveness, and approach relationships with a renewed sense of understanding and compassion. It may indicate a time of healing and making amends, leading to greater harmony and growth in your love life.",
    money:"In terms of finances, The Judgment card signifies a financial awakening and a call to make wise financial decisions. It advises you to evaluate your financial situation objectively and make necessary changes or adjustments. This card encourages you to take responsibility for your financial well-being, learn from past mistakes, and make informed choices that align with your long-term financial goals. It may indicate a time of financial rebirth or opportunities for financial growth and abundance.",
    career:"The Judgment card in a career context represents a period of self-reflection and reassessment of your professional path. It suggests that you are being called to evaluate your career choices, strengths, and aspirations. This card encourages you to embrace personal growth, learn from past experiences, and make empowered decisions that align with your true calling. It may indicate a time of career advancement, discovering your true purpose, or being recognized for your talents and contributions.",
  },
  {
    name:"card52",
    img: require("../cardImages/card52.jpg"),
    love: "The Justice card in love represents fairness, balance, and harmony in relationships. It signifies the need for equality, open communication, and resolving any conflicts or issues with integrity. This card encourages you to seek fairness and truth in your relationships and make decisions based on mutual respect and understanding. It may indicate a time of making important choices that align with your values and bring balance to your love life.",
    money:"In terms of finances, The Justice card signifies financial balance, accountability, and making fair decisions. It advises you to take a balanced and objective approach to your financial matters, considering both your needs and the needs of others involved. This card encourages you to be mindful of your financial responsibilities, make ethical choices, and seek fair outcomes in financial transactions. It may indicate a time of receiving just rewards for your hard work or resolving financial disputes in a fair and equitable manner.",
    career:"The Justice card in a career context represents fairness, integrity, and making just decisions in your professional life. It suggests that you may be facing important career choices or decisions that require careful consideration and ethical judgment. This card encourages you to evaluate your options objectively, weigh the pros and cons, and make choices that align with your values and bring about a sense of fairness and balance in your career. It may indicate a time of seeking professional justice, receiving recognition for your work, or resolving work-related disputes in a fair and equitable manner.",
  },
  {
    name:"card53",
    img: require("../cardImages/card53.jpg"),
    love: "The King of Cups embodies wise and emotionally mature love. It represents emotional stability, empathy, and leadership in relationships. It symbolizes a figure who is emotionally grounded and able to navigate relationships with wisdom and compassion. It suggests the ability to offer emotional support and lead with emotional intelligence.",
    money:"Financially, the King of Cups signifies financial stability through emotional intelligence and balanced financial decisions. It suggests making financial choices that align with one's emotional well-being and values. It emphasizes the importance of maintaining emotional balance in financial matters and using intuition and wisdom to achieve financial stability.",
    career:"In terms of career, the King of Cups represents leadership positions in careers that involve emotional intelligence, counseling, or creative pursuits. It suggests the ability to lead with empathy, make sound decisions based on emotional insight, and foster a supportive and harmonious work environment. It encourages utilizing emotional intelligence and wisdom to guide others and achieve professional success.",
  },
  {
    name:"card54",
    img: require("../cardImages/card54.jpg"),
    love: "The Knight of Wands represents passion, action, and a driving force in love. It signifies a partner who is adventurous, charismatic, and full of energy. It suggests the importance of taking bold action, pursuing desires, and embracing passion within a relationship.",
    money:" Financially, the Knight of Wands indicates financial opportunities or ventures that require boldness, action, and risk-taking. It represents a proactive and ambitious approach to financial matters. It encourages seizing opportunities, taking calculated risks, and utilizing one's passion and drive to manifest financial success.",
    career:" In a career context, the Knight of Wands represents a dynamic and enthusiastic approach to professional endeavors. It suggests pursuing one's career goals with passion, taking bold and decisive action, and embracing new opportunities. It encourages being adventurous, charismatic, and using one's energy to propel career growth and achieve professional success. ",
  },
  {
    name:"card55",
    img: require("../cardImages/card55.jpg"),
    love: "The Knight of Cups represents romantic love or a romantic pursuit. It signifies a charming and charismatic partner who brings a sense of romance, passion, and emotional depth to relationships. It suggests a knight in shining armor, someone who is idealistic and wears their heart on their sleeve. |",
    money:" Financially, the Knight of Cups indicates financial opportunities that require creativity or charisma. It suggests that financial success may come through pursuing ventures that align with one's passions, talents, or artistic abilities. It encourages using emotional intelligence and charm in financial matters.",
    career:" In a career context, the Knight of Cups signifies careers in the arts, counseling, or professions that require emotional intelligence and connection. It suggests pursuing a career path that allows for creative expression, emotional connection with others, and the ability to inspire and uplift. It encourages following one's heart's desires and embracing opportunities that align with one's emotional well-being.",
  },
  {
    name:"card56",
    img: require("../cardImages/card56.jpg"),
    love: " The Knight of Pentacles represents reliability, diligence, and practicality in love. It signifies a committed and dependable partner who values stability and takes a methodical approach to relationships. It suggests a relationship built on trust, loyalty, and the willingness to put in the necessary effort for long-term success.",
    money:"Financially, the Knight of Pentacles indicates financial stability through hard work and practicality. It represents a diligent and disciplined approach to managing finances and building wealth. It encourages long-term financial planning, making careful financial decisions, and staying committed to financial goals.",
    career:"In a career context, the Knight of Pentacles signifies a strong work ethic, reliability, and a methodical approach to professional endeavors. It suggests taking a practical and patient approach to career development, focusing on long-term goals, and being thorough in one's work. It encourages being dependable, dedicated, and committed to achieving professional success through hard work and perseverance.",
  },
  {
    name:"card57",
    img: require("../cardImages/card57.png"),
    love: "The Knight of Swords represents assertiveness, ambition, and action-oriented energy in love. It signifies a partner who is driven, passionate, and direct in their approach to relationships. It suggests the importance of clear communication, assertiveness, and taking decisive action to pursue romantic goals and overcome challenges.",
    money:"Financially, the Knight of Swords indicates financial ambition and assertiveness. It represents a proactive and goal-oriented approach to money matters. It encourages taking calculated risks, seeking new financial opportunities, and using assertiveness to negotiate favorable financial outcomes.",
    career:"In a career context, the Knight of Swords represents a determined and action-oriented approach to professional endeavors. It suggests taking bold and decisive steps towards career goals, embracing challenges, and asserting oneself in the workplace. It encourages being assertive, proactive, and ambitious in order to achieve professional success and advancement.",
  },
  {
    name:"card58",
    img: require("../cardImages/card58.jpg"),
    love: "The King of Pentacles embodies wealth, abundance, and mastery in love. It signifies a partner who is grounded, reliable, and financially successful. It represents a relationship built on stability, security, and the ability to provide for loved ones. It suggests the importance of responsible leadership and practical wisdom within a relationship.",
    money:"Financially, the King of Pentacles indicates financial mastery, wealth, and success. It represents a strong and stable financial foundation, often achieved through disciplined planning, hard work, and wise investments. It encourages taking a leadership role in managing finances, making prudent financial decisions, and enjoying the rewards of financial abundance.",
    career:" In a career context, the King of Pentacles signifies professional success, wealth, and stability. It represents a position of authority and leadership in the workplace, built on practical wisdom and a strong work ethic. It encourages taking a responsible and disciplined approach to professional endeavors, leading by example, and achieving long-term career goals through diligent effort and financial acumen. ",
  },
  {
    name:"card59",
    img: require("../cardImages/card59.png"),
    love: "The King of Swords embodies wisdom, intellect, and clear judgment in love. It signifies a partner who is wise, authoritative, and possesses excellent communication skills. It suggests the importance of rational thinking, fair decision-making, and honest communication within a relationship. It encourages embracing intellectual stimulation, fostering open and respectful dialogue, and maintaining a balanced and harmonious partnership. ",
    money:"Financially, the King of Swords indicates financial intelligence and strategic planning. It represents making informed financial decisions, utilizing one's analytical abilities, and seeking professional advice when necessary. It encourages taking a logical and objective approach to money matters, setting clear financial goals, and making choices that align with long-term financial stability and success.",
    career:"In a career context, the King of Swords represents leadership, expertise, and logical thinking. It suggests a professional approach that is fair, authoritative, and based on sound judgment. It encourages embracing one's intellectual abilities, taking on leadership roles, and using clear communication and logical thinking to navigate professional challenges and achieve career success.",
  },
  {
    name:"card60",
    img: require("../cardImages/card60.jpg"),
    love: "The King of Wands embodies leadership, vision, and entrepreneurial spirit in love. It signifies a partner who is confident, inspiring, and takes charge within a relationship. It represents a relationship characterized by passion, ambition, and the pursuit of shared goals. It suggests the importance of embracing one's personal power and leading with integrity and enthusiasm.",
    money:"Financially, the King of Wands indicates financial leadership, success, and the ability to manifest one's vision. It represents utilizing one's entrepreneurial spirit, strategic thinking, and leadership skills to achieve financial goals. It encourages taking calculated risks, embracing opportunities, and using personal power to create financial abundance and prosperity.",
    career:"In a career context, the King of Wands represents professional leadership, vision, and the ability to inspire and influence others. It suggests taking charge of one's career path, utilizing entrepreneurial skills, and leading with confidence and enthusiasm. It encourages embracing leadership opportunities, setting ambitious goals, and using one's personal power and vision to achieve career success and make a positive impact in the professional sphere.",
  },
  {
    name:"card61",
    img: require("../cardImages/card61.jpg"),
    love: "The Lovers card represents deep connections, choices, and partnerships in love. It signifies a significant relationship or a choice between two paths in matters of the heart. This card encourages you to align your heart and mind, seek harmony, and make decisions based on love and mutual understanding. It may indicate a time of soulmate connections, romantic unions, or a need to choose between different romantic options.",
    money:"In terms of finances, The Lovers card suggests financial decisions that align with your values and passions. It advises you to consider your financial choices carefully and choose paths that resonate with your authentic self. This card encourages you to seek financial endeavors that bring you joy and fulfillment, while also considering the practical aspects. It may indicate a time of financial partnerships or making choices that reflect your true values and long-term financial well-being.",
    career:"The Lovers card in a career context represents choices, partnerships, and alignment in your professional life. It suggests that you may be facing important career decisions or considering collaborations with others. This card encourages you to follow your passion, seek harmonious working relationships, and make choices that align with your values and professional aspirations. It may indicate a time of career partnerships, creative collaborations, or choosing a path that brings fulfillment and balance to your professional life.",
  },
  {
    name:"card62",
    img: require("../cardImages/card62.jpg"),
    love: "The Magician card in love represents the power of manifestation and the potential for new and exciting romantic opportunities. It signifies a time of personal empowerment and taking the initiative in matters of the heart. This card encourages you to tap into your inner resources, communicate effectively, and use your charm and creativity to attract the kind of love you desire. It may indicate a time of confidence, magnetism, and successfully manifesting a fulfilling romantic connection.",
    money:"In terms of finances, The Magician card signifies financial resourcefulness, abundance, and utilizing your skills effectively. It advises you to tap into your talents, think creatively, and seize opportunities to enhance your financial situation. This card encourages you to take an active role in managing your finances and make smart investments or decisions to generate wealth. It may indicate a time of financial growth, successful negotiations, or the manifestation of financial goals through your own abilities.",
    career:"The Magician card in a career context represents success through innovation and resourcefulness. It signifies the power to create and manifest your professional goals. This card encourages you to tap into your unique talents, skills, and expertise to make a significant impact in your career. It suggests that you have the ability to take the lead, be persuasive, and seize opportunities to advance professionally. The Magician card may indicate a time of career breakthroughs, creative problem-solving, and the ability to manifest your desired outcomes in your chosen field.",
  },
  {
    name:"card63",
    img: require("../cardImages/card63.jpg"),
    love: "The Moon card in love represents deep emotions, intuition, and the exploration of the subconscious in relationships. It signifies a time of heightened sensitivity and hidden aspects coming to the surface. This card encourages you to trust your instincts, navigate through uncertainties, and embrace the mystery of love. It may indicate a time of emotional depth, intuitive connections, and the need to confront fears or illusions within a relationship.",
    money:"In terms of finances, The Moon card suggests a need for caution and careful evaluation of your financial situation. It advises you to pay attention to any hidden or unseen factors that may impact your financial stability. This card encourages you to trust your instincts and seek clarity in financial decisions. It may indicate a period of financial fluctuations, the need for financial introspection, or the importance of being mindful of potential risks or hidden information.",
    career:"The Moon card in a career context represents intuition, creativity, and exploring the depths of your professional path. It suggests that you may be navigating through uncertainties or facing hidden challenges in your career. This card encourages you to trust your instincts and delve into your creative and intuitive abilities to find solutions and make informed decisions. It may indicate a time of exploring new avenues, embracing change, and trusting your inner guidance to navigate through professional challenges.",
  },
  {
    name:"card64",
    img: require("../cardImages/card64.jpg"),
    love: "The Page of Pentacles represents practicality, ambition, and new opportunities in love. It signifies the arrival of a young and enthusiastic energy in relationships, often bringing a sense of dedication, loyalty, and a practical approach to love. It suggests new beginnings and the potential for growth and stability.",
    money:"Financially, the Page of Pentacles indicates financial opportunities or messages related to practical and tangible matters. It represents the willingness to learn, develop new skills, and invest in one's financial future. It encourages a diligent and practical approach to money management and being open to new financial ventures.",
    career:"In terms of career, the Page of Pentacles signifies the start of a new job, an apprenticeship, or a career opportunity that offers growth potential. It suggests a practical and dedicated approach to work, a willingness to learn and develop skills, and a focus on long-term career prospects. It encourages embracing new opportunities, taking calculated risks, and building a solid foundation for future professional success. ",
  },
  {
    name:"card65",
    img: require("../cardImages/card65.png"),
    love: "The Page of Swords represents curiosity, intellectual growth, and new perspectives in love. It signifies the arrival of a youthful and inquisitive energy in relationships, bringing forth the exploration of new ideas, communication, and the pursuit of knowledge within a partnership. It suggests the importance of open-mindedness and intellectual stimulation in fostering a healthy and dynamic connection.",
    money:"Financially, the Page of Swords indicates financial opportunities that require analysis, research, or intellectual acuity. It represents the need for financial prudence, utilizing critical thinking skills, and being open to new financial strategies. It encourages seeking financial knowledge, embracing innovative ideas, and making informed financial decisions for long-term success.",
    career:"In terms of career, the Page of Swords signifies the exploration of new ideas, intellectual growth, and the pursuit of knowledge in the professional realm. It suggests seeking opportunities for learning and skill development, embracing intellectual challenges, and being open to new approaches in one's chosen career path. It encourages utilizing communication skills, analytical thinking, and curiosity to achieve professional growth and success.",
  },
  {
    name:"card66",
    img: require("../cardImages/card66.jpg"),
    love: "The Page of Wands represents enthusiasm, exploration, and new opportunities in love. It signifies the arrival of a youthful and adventurous energy in relationships, often bringing new ideas, passion, and a sense of curiosity. It suggests embracing new experiences, expressing oneself creatively, and being open to the possibilities of love.",
    money:"Financially, the Page of Wands indicates financial opportunities or messages related to new ventures or creative projects. It represents the need to be open to innovative financial ideas, take calculated risks, and embrace a proactive approach to money matters. It encourages exploring new financial opportunities, nurturing entrepreneurial spirit, and using creativity to manifest financial growth and success. ",
    career:"In terms of career, the Page of Wands represents the exploration of new career paths, creative projects, or professional opportunities. It suggests embracing a curious and adventurous mindset, being open to learning, and taking the initiative to pursue new professional experiences. It encourages tapping into one's creative potential, seeking mentorship or guidance, and using enthusiasm and passion to propel one's career forward.",
  },
  {
    name:"card67",
    img: require("../cardImages/card67.jpg"),
    love: "The Page of Cups represents creative and intuitive love, emotional messages, or new emotional experiences in relationships. It symbolizes a youthful and imaginative energy that brings a fresh perspective to love. It suggests the arrival of emotional news or the exploration of new emotional depths within relationships.",
    money:" Financially, the Page of Cups indicates financial opportunities or messages related to emotions or creativity. It suggests being open to new financial ventures that involve artistic or imaginative pursuits. It encourages embracing intuition and following creative and unconventional paths to achieve financial success and emotional fulfillment.",
    career:"In terms of career, the Page of Cups signifies careers in the arts, writing, or creative industries. It suggests opportunities for emotional growth and exploration within the workplace, where creativity and intuition are valued. It encourages following one's artistic passions and finding innovative approaches to work, fostering emotional connection and fulfillment in professional endeavors.",
  },
  {
    name:"card68",
    img: require("../cardImages/card68.png"),
    love: "The Queen of Cups represents compassionate and nurturing love, emotional support, and understanding. It symbolizes a wise and empathetic figure who provides emotional stability and guidance in relationships. It suggests the ability to connect deeply with others on an emotional level and offer comfort and support.",
    money:"Financially, the Queen of Cups signifies financial security through intuitive decision-making and nurturing financial choices. It suggests using emotional intelligence to make sound financial decisions and create a stable and secure financial foundation. It emphasizes the importance of balancing emotions and practicality when it comes to money matters.",
    career:" In a career context, the Queen of Cups represents careers in counseling, healing, or professions that involve nurturing and emotional support. It suggests working in environments that value emotional intelligence and empathy. It emphasizes the ability to offer guidance, support, and comfort to others in a professional setting, creating a positive and nurturing work atmosphere.",
  },
  {
    name:"card69",
    img: require("../cardImages/card69.jpg"),
    love: "The Queen of Pentacles represents nurturing, abundance, and practical wisdom in love. It symbolizes a caring and supportive partner who creates a secure and nurturing environment within a relationship. It suggests the ability to provide emotional and material support to loved ones.",
    money:" Financially, the Queen of Pentacles signifies financial security and abundance through practical wisdom. It represents sound financial management, nurturing investments, and a focus on long-term financial stability. It encourages making financial decisions based on practicality, cultivating financial independence, and creating a secure financial foundation. ",
    career:"In terms of career, the Queen of Pentacles represents careers that involve nurturing, providing practical support, and creating a stable work environment. It suggests finding fulfillment through work that aligns with practical wisdom and offers opportunities for growth. It encourages using practical skills, resourcefulness, and nurturing qualities to achieve professional success and create a harmonious work-life balance.",
  },
  {
    name:"card70",
    img: require("../cardImages/card70.jpg"),
    love: "The Queen of Swords represents mental clarity, independence, and discernment in love. It symbolizes a partner who is intelligent, independent, and possesses sharp analytical skills. It suggests the importance of clear communication, setting boundaries, and making decisions based on rationality and emotional detachment within a relationship. ",
    money:"Financially, the Queen of Swords indicates financial independence and discernment. It represents a strategic and analytical approach to money matters. It encourages making informed financial decisions, setting clear financial goals, and utilizing one's intelligence and rationality to achieve financial stability and success.",
    career:"In terms of career, the Queen of Swords represents a professional approach that is logical, objective, and independent. It suggests making decisions based on careful analysis, setting boundaries in the workplace, and utilizing one's intellectual abilities to achieve career advancement. It encourages embracing independence, assertiveness, and discernment to navigate professional challenges and foster personal growth.",
  },
  {
    name:"card71",
    img: require("../cardImages/card71.jpg"),
    love: "The Queen of Wands represents confidence, creativity, and leadership in love. It symbolizes a partner who is charismatic, independent, and radiates a powerful energy. It suggests the importance of self-assuredness, embracing one's passions, and leading with warmth and authenticity within a relationship.",
    money:"Financially, the Queen of Wands indicates financial independence, creativity, and the ability to lead in financial matters. It represents utilizing one's unique talents and passions to create financial abundance. It encourages taking ownership of financial decisions, embracing creativity in money matters, and exuding confidence in financial pursuits.",
    career:"In terms of career, the Queen of Wands represents leadership, charisma, and a creative approach to professional endeavors. It suggests taking charge of one's career, embracing confidence, and using personal power to influence and inspire others. It encourages utilizing creative abilities, leading with authenticity, and nurturing a positive and empowering work environment to achieve professional success and fulfillment.",
  },
  {
    name:"card72",
    img: require("../cardImages/card72.jpg"),
    love: "The Star card in love represents hope, healing, and renewed faith in romantic relationships. It signifies a time of emotional recovery, optimism, and a sense of serenity. This card encourages you to believe in the power of love and have faith that positive things are on the horizon. It may indicate a time of deep emotional connections, renewed hope, and the manifestation of dreams in your love life.",
    money:"In terms of finances, The Star card signifies financial blessings and abundance. It advises you to have faith in your financial journey and trust that your needs will be met. This card encourages you to set financial goals and work towards them with a positive mindset. It may indicate a time of financial stability, successful investments, or receiving unexpected financial support. The Star card reminds you to maintain a sense of optimism and believe in your financial potential.",
    career:"The Star card in a career context represents inspiration, success, and finding your true calling. It suggests that you are on the right path professionally and that your efforts will be rewarded. This card encourages you to follow your passion, trust your instincts, and believe in your unique abilities. It may indicate a time of career growth, recognition for your talents, or finding fulfillment in your work. The Star card reminds you to stay focused on your goals and maintain a positive attitude in your professional endeavors.",
  },
  {
    name:"card73",
    img: require("../cardImages/card73.jpg"),
    love: "The Strength card in love represents inner strength, compassion, and courage in relationships. It signifies a time of overcoming challenges, taming inner conflicts, and embracing love with a gentle and understanding heart. This card encourages you to have patience, show kindness, and demonstrate emotional resilience in your relationships. It may indicate a time of deep emotional connection, loyalty, and the ability to navigate through difficult situations with grace and understanding.",
    money:" In terms of finances, The Strength card suggests financial stability and the ability to overcome obstacles. It advises you to have confidence in your financial abilities and trust your instincts when making money-related decisions. This card encourages you to stay disciplined, persevere through challenges, and tap into your inner strength to achieve financial success. It may indicate a time of financial growth, stability, and the ability to navigate financial setbacks with resilience.",
    career:"The Strength card in a career context represents personal power, resilience, and leadership in the workplace. It suggests that you have the strength and determination to overcome professional challenges and achieve your goals. This card encourages you to believe in your skills, take initiative, and handle difficult situations with grace and assertiveness. It may indicate a time of career advancement, asserting your authority, and demonstrating leadership qualities that lead to success. The Strength card reminds you to trust in your abilities and stay resilient in your professional endeavors.",
  },
  {
    name:"card74",
    img: require("../cardImages/card74.jpg"),
    love: " The Sun card in love represents joy, happiness, and fulfillment in relationships. It signifies a period of radiant love, warmth, and positivity. This card encourages you to embrace the present moment, celebrate your connection with your partner, and express your authentic self. It may indicate a time of deep emotional contentment, strong bonds, and a harmonious partnership filled with love and joy.",
    money:"In terms of finances, The Sun card signifies financial abundance, success, and prosperity. It advises you to embrace a positive mindset and have confidence in your financial endeavors. This card encourages you to pursue opportunities with enthusiasm and optimism, as they have the potential to bring financial rewards. It may indicate a time of financial stability, successful ventures, and the fulfillment of financial goals and aspirations.",
    career:"The Sun card in a career context represents success, recognition, and fulfillment in your professional life. It suggests that you are on the right path and that your hard work and dedication will pay off. This card encourages you to shine brightly, showcase your talents, and take pride in your achievements. It may indicate a time of career advancement, public recognition for your work, and a sense of fulfillment and satisfaction in your chosen career path.",
  },
  {
    name:"card75",
    img: require("../cardImages/card75.jpg"),
    love: "The Temperance card in love represents balance, patience, and harmony in relationships. It signifies a time of emotional healing, compromise, and finding a middle ground. This card encourages you to approach your relationships with moderation, understanding, and a willingness to work together. It may indicate a time of emotional stability, harmonious partnerships, and the blending of different energies to create a loving and balanced connection.",
    money:"In terms of finances, The Temperance card suggests the need for balance and moderation in your financial matters. It advises you to find a harmonious approach to money management, avoiding extremes and impulsive decisions. This card encourages you to practice patience, budgeting, and finding a middle ground between spending and saving. It may indicate a time of financial stability, the need for financial planning, and making wise choices to achieve long-term financial equilibrium.",
    career:"The Temperance card in a career context represents finding balance and harmony in your professional life. It suggests the need for moderation, patience, and a calm approach to your work. This card encourages you to blend different skills, perspectives, and work styles to create a harmonious work environment. It may indicate a time of career growth through collaboration, adapting to change with grace, and finding a balance between work and personal life. The Temperance card reminds you to approach your career with a steady and measured approach.",
  },
  {
    name:"card76",
    img: require("../cardImages/card76.jpg"),
    love: "The Tower card in love represents sudden upheaval, transformation, and releasing of old patterns in relationships. It signifies a time of significant change and unexpected events that may disrupt the current dynamics. This card encourages you to embrace these changes as opportunities for growth, even if they initially feel challenging. It may indicate the need to let go of unhealthy relationship patterns or beliefs that no longer serve you in order to build a stronger foundation for love.",
    money:"In terms of finances, The Tower card suggests unexpected and disruptive changes in your financial situation. It advises you to be prepared for financial challenges or sudden shifts that may require you to adapt and make difficult decisions. This card encourages you to see these changes as opportunities for growth and reevaluating your financial strategies. It may indicate a period of financial instability or the need to reassess your investments, spending habits, or career choices to rebuild your financial foundation.",
    career:"The Tower card in a career context represents sudden upheaval and unexpected changes in your professional life. It suggests that a significant event or disruption may occur that challenges your current career path or work environment. This card encourages you to be resilient, adaptable, and open to new possibilities that may arise from these changes. It may indicate a time of career transformation, the need to let go of old structures or beliefs, and rebuilding your professional path on stronger foundations.",
  },
  {
    name:"card77",
    img: require("../cardImages/card77.jpg"),
    love: "The Wheel of Fortune card in love represents a turning point, destiny, and cycles in relationships. It signifies that the tides of love are shifting, and new opportunities or changes may be on the horizon. This card encourages you to embrace the flow of life and trust in the unfolding of your romantic journey. It may indicate a time of fated encounters, significant relationship milestones, or the need to adapt to changes within your partnership.",
    money:"In terms of finances, The Wheel of Fortune card suggests cycles of financial gain and fluctuations. It signifies that your financial situation is subject to changes and shifts. This card encourages you to seize opportunities when they arise and be prepared for unexpected turns. It may indicate a time of financial breakthroughs, fortunate investments, or the need to make strategic decisions to navigate financial ups and downs.",
    career:"The Wheel of Fortune card in a career context represents changes, luck, and cycles in your professional life. It signifies that your career path is subject to shifts and transformations. This card encourages you to embrace change and be open to new opportunities that come your way. It may indicate a time of career advancement, unexpected career changes, or the need to adapt your skills to evolving circumstances. The Wheel of Fortune card reminds you to remain adaptable and make the most of the opportunities that align with your goals.",
  },
  {
    name:"card78",
    img: require("../cardImages/card78.jpg"),
    love: "The World card in love represents completion, fulfillment, and unity in relationships. It signifies a sense of harmony, wholeness, and deep connection with your partner. This card encourages you to celebrate the accomplishments and growth within your relationship. It may indicate a time of reaching a significant milestone, experiencing a deep sense of love and fulfillment, or finding a soulmate connection that brings a sense of completion to your love life.",
    money:" In terms of finances, The World card suggests financial success, abundance, and achievement. It signifies that you have reached a state of financial stability and accomplishment. This card encourages you to celebrate your financial achievements and maintain a balanced approach to managing your resources. It may indicate a time of reaping the rewards of your hard work, successful investments, or the attainment of your financial goals.",
    career:"The World card in a career context represents professional fulfillment, completion of a project, and success in your chosen field. It signifies that you have reached a stage of mastery and recognition in your career. This card encourages you to embrace your achievements, celebrate your skills, and consider new horizons for further growth. It may indicate a time of career advancement, recognition for your expertise, or the completion of a significant project that brings a sense of fulfillment and satisfaction.",
  },
];

export {tarotCardMeanings};